// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type FooterDocumentDataSlicesSlice = FooterSlice;

/**
 * Content for footer documents
 */
interface FooterDocumentData {
  /**
   * Slice Zone field in *footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | BentoGridSectionSlice
  | HeroSlice
  | FooterSlice
  | MainMenuSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = FooterDocument | PageDocument;

/**
 * Item in *BentoGridSection → Default → Primary → card*
 */
export interface BentoGridSectionSliceDefaultPrimaryCardItem {
  /**
   * icon field in *BentoGridSection → Default → Primary → card*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.default.primary.card[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<"cog" | "sparkles" | "globe" | "people" | "book">;

  /**
   * card_heading field in *BentoGridSection → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.default.primary.card[].card_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_heading: prismic.RichTextField;

  /**
   * card_body field in *BentoGridSection → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.default.primary.card[].card_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_body: prismic.RichTextField;
}

/**
 * Item in *BentoGridSection → without_grid → Primary → card*
 */
export interface BentoGridSectionSliceWithoutGridPrimaryCardItem {
  /**
   * icon field in *BentoGridSection → without_grid → Primary → card*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.withoutGrid.primary.card[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<"cog" | "sparkles" | "globe" | "people" | "book">;

  /**
   * card_heading field in *BentoGridSection → without_grid → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.withoutGrid.primary.card[].card_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_heading: prismic.RichTextField;

  /**
   * card_body field in *BentoGridSection → without_grid → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.withoutGrid.primary.card[].card_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_body: prismic.RichTextField;
}

/**
 * Primary content in *BentoGridSection → Default → Primary*
 */
export interface BentoGridSectionSliceDefaultPrimary {
  /**
   * heading field in *BentoGridSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *BentoGridSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * card field in *BentoGridSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card: prismic.GroupField<
    Simplify<BentoGridSectionSliceDefaultPrimaryCardItem>
  >;
}

/**
 * Default variation for BentoGridSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoGridSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BentoGridSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *BentoGridSection → without_grid → Primary*
 */
export interface BentoGridSectionSliceWithoutGridPrimary {
  /**
   * heading field in *BentoGridSection → without_grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.withoutGrid.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *BentoGridSection → without_grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.withoutGrid.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * card field in *BentoGridSection → without_grid → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.withoutGrid.primary.card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card: prismic.GroupField<
    Simplify<BentoGridSectionSliceWithoutGridPrimaryCardItem>
  >;
}

/**
 * without_grid variation for BentoGridSection Slice
 *
 * - **API ID**: `withoutGrid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoGridSectionSliceWithoutGrid = prismic.SharedSliceVariation<
  "withoutGrid",
  Simplify<BentoGridSectionSliceWithoutGridPrimary>,
  never
>;

/**
 * Slice variation for *BentoGridSection*
 */
type BentoGridSectionSliceVariation =
  | BentoGridSectionSliceDefault
  | BentoGridSectionSliceWithoutGrid;

/**
 * BentoGridSection Shared Slice
 *
 * - **API ID**: `bento_grid_section`
 * - **Description**: BentoGridSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoGridSectionSlice = prismic.SharedSlice<
  "bento_grid_section",
  BentoGridSectionSliceVariation
>;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * footer-loogo field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footerLogo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  footerLogo: prismic.ImageField<never>;

  /**
   * copyright field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.copyright
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copyright: prismic.RichTextField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Item in *Hero → Default → Primary → location*
 */
export interface HeroSliceDefaultPrimaryLocationItem {
  /**
   * leading field in *Hero → Default → Primary → location*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.location[].leading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  leading: prismic.RichTextField;

  /**
   * body field in *Hero → Default → Primary → location*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.location[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Item in *Hero → With-tint → Primary → location*
 */
export interface HeroSliceWithTintPrimaryLocationItem {
  /**
   * leading field in *Hero → With-tint → Primary → location*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withTint.primary.location[].leading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  leading: prismic.RichTextField;

  /**
   * body field in *Hero → With-tint → Primary → location*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withTint.primary.location[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * bgImage field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.bgimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bgimage: prismic.ImageField<never>;

  /**
   * heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * location field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.location[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  location: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryLocationItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → With-tint → Primary*
 */
export interface HeroSliceWithTintPrimary {
  /**
   * bgImage field in *Hero → With-tint → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withTint.primary.bgimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bgimage: prismic.ImageField<never>;

  /**
   * heading field in *Hero → With-tint → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withTint.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *Hero → With-tint → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withTint.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * location field in *Hero → With-tint → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withTint.primary.location[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  location: prismic.GroupField<Simplify<HeroSliceWithTintPrimaryLocationItem>>;
}

/**
 * With-tint variation for Hero Slice
 *
 * - **API ID**: `withTint`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceWithTint = prismic.SharedSliceVariation<
  "withTint",
  Simplify<HeroSliceWithTintPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceWithTint;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *MainMenu → Default → Primary*
 */
export interface MainMenuSliceDefaultPrimary {
  /**
   * logo field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * buttonText   field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.default.primary.buttontext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontext: prismic.KeyTextField;

  /**
   * buttonLink field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.default.primary.buttonlink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * linkItem field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.default.primary.linkitem
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkitem: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for MainMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MainMenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MainMenuSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MainMenu*
 */
type MainMenuSliceVariation = MainMenuSliceDefault;

/**
 * MainMenu Shared Slice
 *
 * - **API ID**: `main_menu`
 * - **Description**: MainMenu
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MainMenuSlice = prismic.SharedSlice<
  "main_menu",
  MainMenuSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BentoGridSectionSlice,
      BentoGridSectionSliceDefaultPrimaryCardItem,
      BentoGridSectionSliceDefaultPrimary,
      BentoGridSectionSliceWithoutGridPrimaryCardItem,
      BentoGridSectionSliceWithoutGridPrimary,
      BentoGridSectionSliceVariation,
      BentoGridSectionSliceDefault,
      BentoGridSectionSliceWithoutGrid,
      FooterSlice,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryLocationItem,
      HeroSliceDefaultPrimary,
      HeroSliceWithTintPrimaryLocationItem,
      HeroSliceWithTintPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceWithTint,
      MainMenuSlice,
      MainMenuSliceDefaultPrimary,
      MainMenuSliceVariation,
      MainMenuSliceDefault,
    };
  }
}
