// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AboutDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for about documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *about*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *about*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *about*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *about*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * about document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type CalendarDocumentDataSlicesSlice = CalendarHeroSlice;

/**
 * Content for calendar documents
 */
interface CalendarDocumentData {
  /**
   * Slice Zone field in *calendar*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<CalendarDocumentDataSlicesSlice> /**
   * Meta Title field in *calendar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: calendar.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *calendar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: calendar.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *calendar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * calendar document from Prismic
 *
 * - **API ID**: `calendar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CalendarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CalendarDocumentData>,
    "calendar",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | GallerySlice
  | FaqsSlice
  | FooterSlice
  | FirstTimersSlice
  | WordFromOurPastorSlice
  | BentoGridSectionSlice
  | HeroSlice
  | MainMenuSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type MinistriesDocumentDataSlicesSlice = never;

/**
 * Content for ministries documents
 */
interface MinistriesDocumentData {
  /**
   * Slice Zone field in *ministries*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ministries.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<MinistriesDocumentDataSlicesSlice> /**
   * Meta Title field in *ministries*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: ministries.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *ministries*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: ministries.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *ministries*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ministries.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * ministries document from Prismic
 *
 * - **API ID**: `ministries`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MinistriesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MinistriesDocumentData>,
    "ministries",
    Lang
  >;

/**
 * Content for nav documents
 */
interface NavDocumentData {
  /**
   * logo field in *nav*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * link_item field in *nav*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.link_item
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_item: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary" | "Tertiary"
    >
  >;
}

/**
 * nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<NavDocumentData>, "nav", Lang>;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SermonsDocumentDataSlicesSlice = never;

/**
 * Content for sermons documents
 */
interface SermonsDocumentData {
  /**
   * Slice Zone field in *sermons*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sermons.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SermonsDocumentDataSlicesSlice> /**
   * Meta Title field in *sermons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: sermons.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *sermons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: sermons.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *sermons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sermons.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * sermons document from Prismic
 *
 * - **API ID**: `sermons`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SermonsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SermonsDocumentData>,
    "sermons",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | CalendarDocument
  | HomeDocument
  | MinistriesDocument
  | NavDocument
  | PageDocument
  | SermonsDocument;

/**
 * Item in *BentoGridSection → Default → Primary → card*
 */
export interface BentoGridSectionSliceDefaultPrimaryCardItem {
  /**
   * icon field in *BentoGridSection → Default → Primary → card*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.default.primary.card[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    | "LuHeart"
    | "LuBookOpen "
    | "LuUsers "
    | "LuShield"
    | "LuChurch "
    | "LuCompass "
  >;

  /**
   * card_heading field in *BentoGridSection → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.default.primary.card[].card_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_heading: prismic.RichTextField;

  /**
   * card_body field in *BentoGridSection → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.default.primary.card[].card_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_body: prismic.RichTextField;
}

/**
 * Item in *BentoGridSection → without_grid → Primary → card*
 */
export interface BentoGridSectionSliceWithoutGridPrimaryCardItem {
  /**
   * icon field in *BentoGridSection → without_grid → Primary → card*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.withoutGrid.primary.card[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<"cog" | "sparkles" | "globe" | "people" | "book">;

  /**
   * card_heading field in *BentoGridSection → without_grid → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.withoutGrid.primary.card[].card_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_heading: prismic.RichTextField;

  /**
   * card_body field in *BentoGridSection → without_grid → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.withoutGrid.primary.card[].card_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_body: prismic.RichTextField;
}

/**
 * Primary content in *BentoGridSection → Default → Primary*
 */
export interface BentoGridSectionSliceDefaultPrimary {
  /**
   * heading field in *BentoGridSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *BentoGridSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * card field in *BentoGridSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card: prismic.GroupField<
    Simplify<BentoGridSectionSliceDefaultPrimaryCardItem>
  >;
}

/**
 * Default variation for BentoGridSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoGridSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BentoGridSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *BentoGridSection → without_grid → Primary*
 */
export interface BentoGridSectionSliceWithoutGridPrimary {
  /**
   * heading field in *BentoGridSection → without_grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.withoutGrid.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *BentoGridSection → without_grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.withoutGrid.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * card field in *BentoGridSection → without_grid → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid_section.withoutGrid.primary.card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card: prismic.GroupField<
    Simplify<BentoGridSectionSliceWithoutGridPrimaryCardItem>
  >;
}

/**
 * without_grid variation for BentoGridSection Slice
 *
 * - **API ID**: `withoutGrid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoGridSectionSliceWithoutGrid = prismic.SharedSliceVariation<
  "withoutGrid",
  Simplify<BentoGridSectionSliceWithoutGridPrimary>,
  never
>;

/**
 * Slice variation for *BentoGridSection*
 */
type BentoGridSectionSliceVariation =
  | BentoGridSectionSliceDefault
  | BentoGridSectionSliceWithoutGrid;

/**
 * BentoGridSection Shared Slice
 *
 * - **API ID**: `bento_grid_section`
 * - **Description**: BentoGridSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoGridSectionSlice = prismic.SharedSlice<
  "bento_grid_section",
  BentoGridSectionSliceVariation
>;

/**
 * Primary content in *CalendarHero → Default → Primary*
 */
export interface CalendarHeroSliceDefaultPrimary {
  /**
   * heading field in *CalendarHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar_hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *CalendarHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar_hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for CalendarHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CalendarHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CalendarHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CalendarHero*
 */
type CalendarHeroSliceVariation = CalendarHeroSliceDefault;

/**
 * CalendarHero Shared Slice
 *
 * - **API ID**: `calendar_hero`
 * - **Description**: CalendarHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CalendarHeroSlice = prismic.SharedSlice<
  "calendar_hero",
  CalendarHeroSliceVariation
>;

/**
 * Item in *Faqs → Default → Primary → QnAs*
 */
export interface FaqsSliceDefaultPrimaryQnasItem {
  /**
   * heading field in *Faqs → Default → Primary → QnAs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.qnas[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *Faqs → Default → Primary → QnAs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.qnas[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Faqs → Default → Primary*
 */
export interface FaqsSliceDefaultPrimary {
  /**
   * heading field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * link field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * QnAs field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.qnas[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  qnas: prismic.GroupField<Simplify<FaqsSliceDefaultPrimaryQnasItem>>;
}

/**
 * Default variation for Faqs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faqs*
 */
type FaqsSliceVariation = FaqsSliceDefault;

/**
 * Faqs Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqsSlice = prismic.SharedSlice<"faqs", FaqsSliceVariation>;

/**
 * Item in *FirstTimers → Default → Primary → card*
 */
export interface FirstTimersSliceDefaultPrimaryCardItem {
  /**
   * cardTitle field in *FirstTimers → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_timers.default.primary.card[].cardtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cardtitle: prismic.RichTextField;

  /**
   * cardImage field in *FirstTimers → Default → Primary → card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: first_timers.default.primary.card[].cardimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cardimage: prismic.ImageField<never>;

  /**
   * cardContent field in *FirstTimers → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_timers.default.primary.card[].cardcontent
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cardcontent: prismic.RichTextField;
}

/**
 * Primary content in *FirstTimers → Default → Primary*
 */
export interface FirstTimersSliceDefaultPrimary {
  /**
   * heading field in *FirstTimers → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_timers.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * card field in *FirstTimers → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: first_timers.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card: prismic.GroupField<Simplify<FirstTimersSliceDefaultPrimaryCardItem>>;
}

/**
 * Default variation for FirstTimers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FirstTimersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FirstTimersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FirstTimers*
 */
type FirstTimersSliceVariation = FirstTimersSliceDefault;

/**
 * FirstTimers Shared Slice
 *
 * - **API ID**: `first_timers`
 * - **Description**: FirstTimers
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FirstTimersSlice = prismic.SharedSlice<
  "first_timers",
  FirstTimersSliceVariation
>;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * footer-loogo field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footerLogo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  footerLogo: prismic.ImageField<never>;

  /**
   * copyright field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.copyright
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copyright: prismic.RichTextField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Item in *Gallery → Default → Primary → gallery*
 */
export interface GallerySliceDefaultPrimaryGalleryItem {
  /**
   * image field in *Gallery → Default → Primary → gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Gallery → Default → Primary*
 */
export interface GallerySliceDefaultPrimary {
  /**
   * heading field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * gallery field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery: prismic.GroupField<Simplify<GallerySliceDefaultPrimaryGalleryItem>>;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySlice = prismic.SharedSlice<
  "gallery",
  GallerySliceVariation
>;

/**
 * Item in *Hero → Default → Primary → location*
 */
export interface HeroSliceDefaultPrimaryLocationItem {
  /**
   * leading field in *Hero → Default → Primary → location*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.location[].leading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  leading: prismic.RichTextField;

  /**
   * body field in *Hero → Default → Primary → location*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.location[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Item in *Hero → With-tint → Primary → location*
 */
export interface HeroSliceWithTintPrimaryLocationItem {
  /**
   * leading field in *Hero → With-tint → Primary → location*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withTint.primary.location[].leading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  leading: prismic.RichTextField;

  /**
   * body field in *Hero → With-tint → Primary → location*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withTint.primary.location[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * bgImage field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.bgimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bgimage: prismic.ImageField<never>;

  /**
   * heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * location field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.location[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  location: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryLocationItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → With-tint → Primary*
 */
export interface HeroSliceWithTintPrimary {
  /**
   * bgImage field in *Hero → With-tint → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withTint.primary.bgimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bgimage: prismic.ImageField<never>;

  /**
   * heading field in *Hero → With-tint → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withTint.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *Hero → With-tint → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withTint.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * location field in *Hero → With-tint → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withTint.primary.location[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  location: prismic.GroupField<Simplify<HeroSliceWithTintPrimaryLocationItem>>;
}

/**
 * With-tint variation for Hero Slice
 *
 * - **API ID**: `withTint`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceWithTint = prismic.SharedSliceVariation<
  "withTint",
  Simplify<HeroSliceWithTintPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceWithTint;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *MainMenu → Default → Primary*
 */
export interface MainMenuSliceDefaultPrimary {
  /**
   * logo field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * buttonText   field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.default.primary.buttontext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontext: prismic.KeyTextField;

  /**
   * buttonLink field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.default.primary.buttonlink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * linkItem field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.default.primary.linkitem
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkitem: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for MainMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MainMenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MainMenuSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MainMenu*
 */
type MainMenuSliceVariation = MainMenuSliceDefault;

/**
 * MainMenu Shared Slice
 *
 * - **API ID**: `main_menu`
 * - **Description**: MainMenu
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MainMenuSlice = prismic.SharedSlice<
  "main_menu",
  MainMenuSliceVariation
>;

/**
 * Primary content in *WordFromOurPastor → Default → Primary*
 */
export interface WordFromOurPastorSliceDefaultPrimary {
  /**
   * pastor_image field in *WordFromOurPastor → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: word_from_our_pastor.default.primary.pastor_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  pastor_image: prismic.ImageField<never>;

  /**
   * heading field in *WordFromOurPastor → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: word_from_our_pastor.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *WordFromOurPastor → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: word_from_our_pastor.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for WordFromOurPastor Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WordFromOurPastorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WordFromOurPastorSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WordFromOurPastor*
 */
type WordFromOurPastorSliceVariation = WordFromOurPastorSliceDefault;

/**
 * WordFromOurPastor Shared Slice
 *
 * - **API ID**: `word_from_our_pastor`
 * - **Description**: WordFromOurPastor
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WordFromOurPastorSlice = prismic.SharedSlice<
  "word_from_our_pastor",
  WordFromOurPastorSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      CalendarDocument,
      CalendarDocumentData,
      CalendarDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      MinistriesDocument,
      MinistriesDocumentData,
      MinistriesDocumentDataSlicesSlice,
      NavDocument,
      NavDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SermonsDocument,
      SermonsDocumentData,
      SermonsDocumentDataSlicesSlice,
      AllDocumentTypes,
      BentoGridSectionSlice,
      BentoGridSectionSliceDefaultPrimaryCardItem,
      BentoGridSectionSliceDefaultPrimary,
      BentoGridSectionSliceWithoutGridPrimaryCardItem,
      BentoGridSectionSliceWithoutGridPrimary,
      BentoGridSectionSliceVariation,
      BentoGridSectionSliceDefault,
      BentoGridSectionSliceWithoutGrid,
      CalendarHeroSlice,
      CalendarHeroSliceDefaultPrimary,
      CalendarHeroSliceVariation,
      CalendarHeroSliceDefault,
      FaqsSlice,
      FaqsSliceDefaultPrimaryQnasItem,
      FaqsSliceDefaultPrimary,
      FaqsSliceVariation,
      FaqsSliceDefault,
      FirstTimersSlice,
      FirstTimersSliceDefaultPrimaryCardItem,
      FirstTimersSliceDefaultPrimary,
      FirstTimersSliceVariation,
      FirstTimersSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      GallerySlice,
      GallerySliceDefaultPrimaryGalleryItem,
      GallerySliceDefaultPrimary,
      GallerySliceVariation,
      GallerySliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryLocationItem,
      HeroSliceDefaultPrimary,
      HeroSliceWithTintPrimaryLocationItem,
      HeroSliceWithTintPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceWithTint,
      MainMenuSlice,
      MainMenuSliceDefaultPrimary,
      MainMenuSliceVariation,
      MainMenuSliceDefault,
      WordFromOurPastorSlice,
      WordFromOurPastorSliceDefaultPrimary,
      WordFromOurPastorSliceVariation,
      WordFromOurPastorSliceDefault,
    };
  }
}
