// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  main_menu: dynamic(() => import("./MainMenu")),
};
